# Generated by Django 3.2.3 on 2021-06-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_cart_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_selected',
        ),
    ]
