# Generated by Django 3.2.3 on 2021-05-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0003_auto_20210527_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='minimium_order_quantity',
            new_name='minimum_order_quantity',
        ),
    ]
