# Generated by Django 3.2.3 on 2021-05-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0004_rename_minimium_order_quantity_listing_minimum_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '4. Address/Billing Informations'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': '5. Inventories'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': '6. Listings'},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='item_name',
            new_name='name',
        ),
    ]
