# Generated by Django 3.2.3 on 2021-05-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0005_auto_20210527_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genesis.item'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
