# Generated by Django 3.2.3 on 2021-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0007_alter_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PACKED', 'PACKED'), ('SHIPPED', 'SHIPPED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], max_length=200, null=True),
        ),
    ]
