# Generated by Django 3.2.3 on 2021-06-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0010_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genesis.address'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genesis.weight'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genesis.item'),
        ),
    ]
