# Generated by Django 3.2.3 on 2021-06-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0011_auto_20210603_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
