# Generated by Django 3.2.3 on 2021-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0012_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
