# Generated by Django 3.2.3 on 2021-06-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0014_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
