# Generated by Django 3.2.3 on 2021-06-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0015_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '8. Order/Transactions'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='inventory_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purchase_price_per_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight_group',
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_price_per_quantity', models.PositiveIntegerField(default=1)),
                ('inventory_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genesis.inventory')),
                ('item_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genesis.item')),
                ('weight_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genesis.weight')),
            ],
            options={
                'verbose_name_plural': '7. Ordered Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='item_details',
            field=models.ManyToManyField(to='genesis.OrderedItems'),
        ),
    ]
