# Generated by Django 3.2.3 on 2021-06-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0016_auto_20210608_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='item_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genesis.listing'),
        ),
    ]
