# Generated by Django 3.2.3 on 2021-06-11 04:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0018_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rebate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
