# Generated by Django 3.2.3 on 2021-06-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0019_alter_order_rebate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'PLACED'), ('ACCEPTED', 'ACCEPTED'), ('PACKED', 'PACKED'), ('SHIPPED', 'SHIPPED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], max_length=200, null=True),
        ),
    ]
