# Generated by Django 3.2.3 on 2021-06-14 08:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0023_auto_20210611_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='GST_applicable',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='order',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rebate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sgst',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='GST_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='invoice_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='is_igst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='rebate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
