# Generated by Django 3.2.3 on 2021-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0024_auto_20210614_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='total_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
