# Generated by Django 3.2.3 on 2021-06-16 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0025_ordereditems_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{2}\\s{0, 1}[0-9]{3}$', message='Enter a Valid India Pincode')]),
        ),
    ]
