# Generated by Django 3.2.3 on 2021-06-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0026_alter_address_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
