# Generated by Django 3.2.3 on 2021-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0027_alter_address_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], max_length=200, null=True),
        ),
    ]
