# Generated by Django 3.2.3 on 2021-06-24 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genesis', '0032_auto_20210623_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='billing_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='genesis.address'),
        ),
        migrations.AddField(
            model_name='quote',
            name='weight_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='genesis.weight'),
        ),
    ]
