# Generated by Django 3.2.3 on 2021-06-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userchats', '0002_alter_userchats_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchats',
            options={'verbose_name_plural': '1. User Chat Rooms'},
        ),
        migrations.CreateModel(
            name='UserChatsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_chats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userchats.userchats')),
            ],
            options={
                'verbose_name_plural': '1. User Chats Messages',
            },
        ),
    ]
