# Generated by Django 3.2.3 on 2021-06-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userchats', '0003_auto_20210622_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchatsmessage',
            options={'verbose_name_plural': '2. User Chats Messages'},
        ),
        migrations.RemoveField(
            model_name='userchats',
            name='message',
        ),
    ]
