# Generated by Django 3.2.3 on 2021-06-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicknotifications',
            options={'verbose_name_plural': '1. Quick Notifications/Alerts'},
        ),
    ]
